# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1umopWl-KA8fI6h2PpeCZrjNU25jNFO2g
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('train.csv')

df.head()

"""univariet data analysis for numerical categories"""

df['Age'].describe()

df["Age"].plot(kind="kde")

df["Age"].skew()

df["Age"].plot(kind="box")

df[df['Age'] > 65]

df['Age'].isnull().sum()

"""conl:

* age is almost normally distributed
* 20% of values are missing
*  there are some outlier







"""



df['Fare'].describe()

df['Fare'].plot(kind="kde")

df['Fare'].plot(kind="box")

df['Fare'].plot(kind="hist")

df['Fare'].skew()

df[df['Fare'] > 250]

"""conl:
fare is not individual fare
+vly skew date


*   List item
*   List item

#survived col
conl
"""

df['Survived'].value_counts()

df['Sex'].value_counts().plot(kind="bar")

df['Sex'].value_counts().plot(kind="pie",autopct='%0.1f%%')

df['Pclass'].value_counts().plot(kind="pie")

df['SibSp'].value_counts().plot(kind="bar")

df['SibSp'].value_counts().plot(kind="hist")

df['SibSp'].value_counts().plot(kind="pie",autopct='%0.1f%%')

"""bivarient analysis"""

# Age vs Fare
sns.scatterplot(x='Age', y='Fare', data=df)
plt.title('Age vs Fare')
plt.show()

# Age distribution by Gender
sns.boxplot(x='Sex', y='Age', data=df)
plt.title('Age Distribution by Gender')
plt.show()

# Fare distribution by Pclass
sns.boxplot(x='Pclass', y='Fare', data=df)
plt.title('Fare Distribution by Pclass')
plt.show()

# Correlation matrix
plt.figure(figsize=(10,6))
# Set numeric_only=True to exclude non-numeric columns from correlation calculation
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()